apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: planifets-frontend-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: frontend
      path: kv/data/planifets-dev/default/frontend
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: backend
      path: kv/data/planifets-dev/default/backend
  output:
    name: planifets-frontend-secret
    stringData:
      umami_website_id: '{{ .frontend.umami_website_id }}'
      posthog_project_token: '{{ .backend.posthog_project_token }}'
    type: opaque
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: planifets-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: backend
      path: kv/data/planifets-dev/default/backend
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: cnpg
      path: kv/data/planifets-dev/default/cnpg
  output:
    name: planifets-secret
    stringData:
      db_url: 'postgresql://{{ .cnpg.username }}:{{ .cnpg.password }}@cnpg-rw.planifets-dev.svc.cluster.local:5432/planifetsDB?schema=public'
      posthog_api_key: '{{ .backend.posthog_api_key }}'
      chatbot_enabled: '{{ .backend.chatbot_enabled }}'
      gemini_api_key: '{{ .backend.gemini_api_key }}'
      groq_api_key: '{{ .backend.groq_api_key }}'
      nvidia_api_key: '{{ .backend.nvidia_api_key }}'
      qdrant_api_key: '{{ .backend.qdrant_api_key }}'
    type: opaque
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: cnpg-vault-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: db
      path: kv/data/planifets-dev/default/cnpg
  output:
    name: cnpg-secret
    stringData:
      username: '{{ .db.username }}'
      password: '{{ .db.password }}'
    type: kubernetes.io/basic-auth
