apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: root
  namespace: matomo
spec:
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: kv/data/matomo/default
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: user
  namespace: matomo
spec:
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: kv/data/matomo/default
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
