apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-db
  namespace: netbox
spec:
  instances: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  storage:
    size: 5Gi
    storageClass: cephfs
  bootstrap:
    initdb:
      database: netbox
      owner: netbox
