apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pkg-cache
  namespace: pkg-cache
resources:
  - resources/pvc.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/network-policy.yaml
  - resources/certificate.yaml
  - resources/nginx-configmap.yaml
  - resources/httpproxy.yaml
  - resources/dnf-cache-pvc.yaml
  - resources/dnf-cache-configmap.yaml
  - resources/dnf-cache-deployment.yaml
  - resources/dnf-cache-service.yaml
  - resources/dnf-cache-network-policy.yaml
  - resources/dnf-cache-certificate.yaml
  - resources/dnf-cache-httpproxy.yaml
  - resources/pacman-cache-pvc.yaml
  - resources/pacman-cache-configmap.yaml
  - resources/pacman-cache-deployment.yaml
  - resources/pacman-cache-service.yaml
  - resources/pacman-cache-network-policy.yaml
  - resources/pacman-cache-certificate.yaml
  - resources/pacman-cache-httpproxy.yaml
  - resources/freebsd-pkg-cache-pvc.yaml
  - resources/freebsd-pkg-cache-configmap.yaml
  - resources/freebsd-pkg-cache-deployment.yaml
  - resources/freebsd-pkg-cache-service.yaml
  - resources/freebsd-pkg-cache-network-policy.yaml
  - resources/freebsd-pkg-cache-certificate.yaml
  - resources/freebsd-pkg-cache-httpproxy.yaml
  - resources/nix-cache-pvc.yaml
  - resources/nix-cache-configmap.yaml
  - resources/nix-cache-deployment.yaml
  - resources/nix-cache-service.yaml
  - resources/nix-cache-network-policy.yaml
  - resources/nix-cache-certificate.yaml
  - resources/nix-cache-httpproxy.yaml
