apiVersion: garage.rajsingh.info/v1beta2
kind: GarageCluster
metadata:
  name: garage-external
  namespace: garage-external
spec:
  connectTo:
    adminApiEndpoint: http://10.0.21.50:3903
    adminTokenSecretRef:
      name: garage-admin-token
      key: token
