apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: garage-admin-token
  namespace: garage-external
spec:
  vaultAuthRef: garage-external-auth
  type: kv-v1
  mount: kv-system
  path: default_passwords/garage-admin-token
  destination:
    name: garage-admin-token
    create: true
