apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusparent
  annotations:
    kube-score/ignore: pod-networkpolicy,container-image-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campusparent
  template:
    metadata:
      labels:
        app: campusparent
    spec:
      imagePullSecrets:
        - name: ghcr-clubcedille-secret
      containers:
        - name: campusparent
          image: ghcr.io/clubcedille/frontend-campusparentv2:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /run
            - name: config-volume
              mountPath: /etc/nginx/conf.d
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: config-volume
          configMap:
            name: nginx-config
        - name: nginx-run
          emptyDir: {}
