apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: planifets-chatbot-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: qdrant
      path: kv/data/planifets-dev/default/chatbot/qdrant
  output:
    name: planifets-chatbot-secret
    stringData:
      qdrant_api_key: '{{ .qdrant.api_key }}'
    type: opaque