apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/httpproxy.yaml
  - resources/certificate.yaml
helmCharts:
  - name: vaultwarden
    version: "0.31.8"
    repo: https://guerzon.github.io/vaultwarden
    releaseName: "vaultwarden"
    namespace: vaultwarden
    valuesFile: "helm/values.yaml"
patches:
  - target:
      kind: Service
      name: vaultwarden
      namespace: vaultwarden
    patch: |-
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8080