apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-shared
    namespace: vaultwarden
  project: k8s-shared
  sources:
    - repoURL: https://github.com/ClubCedille/k8s-shared.git
      path: apps/vaultwarden
      targetRevision: HEAD
   - chart: vaultwarden
      helm:
        releaseName: vaultwarden
        valueFiles:
          - $values/apps/vaultwarden/helm/values.yaml
      repoURL: https://guerzon.github.io/vaultwarden
      targetRevision: 0.34.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
