apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: sonarqube-postgres-secret-sync
  namespace: sonarqube
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: user
      path: kv/data/sonarqube/default/user

  output:
    name: postgres-secret-sonarqube
    stringData:
      username: 'sonarqube'
      password: '{{ .user.password }}'
    type: Opaque
    labels:
      app: sonarqube
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: sonarqube-secret-sync
  namespace: sonarqube
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: monitoring
      path: kv/data/sonarqube/default/monitoring
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: admin
      path: kv/data/sonarqube/default/admin

  output:
    name: sonarqube-secrets
    stringData:
      monitoringPasscode: '{{ .monitoring.password }}'
      password: '{{ .admin.password }}'
      currentPassword: 'admin'
    type: Opaque
    labels:
      app: sonarqube