apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: user
  namespace: sonarqube
spec:
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: kv/data/sonarqube/default
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: monitoring
  namespace: sonarqube
spec:
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: kv/data/sonarqube/default
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: admin
  namespace: sonarqube
spec:
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: kv/data/sonarqube/default
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy