apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: littlelink-tls
  namespace: littlelink
spec:
  secretName: littlelink-tls
  issuerRef:
    name: letsencrypt-etsmtl
    kind: ClusterIssuer
  commonName: littlelink.etsmtl.club
  dnsNames:
    - littlelink.etsmtl.club