apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: campusparent
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: webapp=ghcr.io/campusparent-aufets/campusparent:1.0.2
    argocd-image-updater.argoproj.io/webapp.update-strategy: digest
    argocd-image-updater.argoproj.io/webapp.pull-secret: pullsecret:argocd/ghcr-campusparent-secret
spec:
  project: k8s-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: campusparent
  source:
    repoURL: https://github.com/ClubCedille/k8s-shared
    path: apps/clubs/campusparent/website/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
