apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docmost-tls
spec:
  secretName: docmost-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: docmost.shared.cedille.club
  dnsNames:
    - docmost.shared.cedille.club