apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docmost-tls
spec:
  secretName: docmost-tls
  issuerRef:
    name: letsencrypt-etsmtl
    kind: ClusterIssuer
  commonName: wiki.etsmtl.club
  dnsNames:
    - wiki.etsmtl.club
