apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docmost-tls
spec:
  secretName: docmost-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: docmost.etsmtl.club
  dnsNames:
    - docmost.etsmtl.club