apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: docmost-shared
spec:
  virtualhost:
    fqdn: docmost.shared.cedille.club
    tls:
      secretName: docmost-shared-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: docmost
          port: 3000
      timeoutPolicy:
        idle: 600s
        response: 600s
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: docmost
spec:
  virtualhost:
    fqdn: docmost.etsmtl.club
    tls:
      secretName: docmost-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: docmost
          port: 3000
      timeoutPolicy:
        idle: 600s
        response: 600s