apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dci-summercampbot
spec:
  secretName: dci-summercampbot
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: summercampbot.dciets.etsmtl.club
  dnsNames:
    - summercampbot.dciets.etsmtl.club
