apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml
  - ingress-algoets.yaml
  - configMap.yaml
  - vault-secret.yaml

patches:
  - path: patch-api-token-salt.yaml
