apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: markets-api-token-salt
spec:
  refreshPeriod: 1h0m0s
  refreshThreshold: 90
  syncOnResourceChange: false
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: markets
      path: kv/data/markets/default/config
      requestType: GET
  output:
    name: markets-api-token-salt
    stringData:
      API_TOKEN_SALT: '{{ .markets.API_TOKEN_SALT }}'
    type: opaque
