apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-etsmtl
    kind: ClusterIssuer
  commonName: auth.etsmtl.club
  dnsNames:
    - auth.etsmtl.club
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-internal-tls
  namespace: authentik
spec:
  secretName: authentik-internal-tls
  issuerRef:
    name: letsencrypt-etsmtl-internal
    kind: ClusterIssuer
  commonName: auth.etsmtl.club
  dnsNames:
    - auth.etsmtl.club