apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: auth.etsmtl.club
  dnsNames:
    - auth.etsmtl.club