apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-etsmtl
    kind: ClusterIssuer
  commonName: auth.etsmtl.club
  dnsNames:
    - auth.etsmtl.club
