apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: authentik
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  virtualhost:
    fqdn: authentik.shared.cedille.club
    tls:
      secretName: authentik-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%REQ(X-Forwarded-For)%"
        - name: X-Forwarded-Proto
          value: "%REQ(:scheme)%"
    services:
    - name: authentik-server
      port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: authentik-internal
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour-internal
  virtualhost:
    fqdn: authentik.shared.cedille.club
    tls:
      secretName: authentik-internal-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%REQ(X-Forwarded-For)%"
        - name: X-Forwarded-Proto
          value: "%REQ(:scheme)%"
    services:
    - name: authentik-server
      port: 80