apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: authentik
  namespace: authentik
spec:
  virtualhost:
    fqdn: auth.etsmtl.club
    tls:
      secretName: authentik-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%REQ(X-Forwarded-For)%"
        - name: X-Forwarded-Proto
          value: "%REQ(:scheme)%"
    services:
    - name: authentik-server
      port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: authentik-internal
  namespace: authentik
spec:
  ingressClassName: contour-internal
  virtualhost:
    fqdn: auth.etsmtl.club
    tls:
      secretName: authentik-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%REQ(X-Forwarded-For)%"
        - name: X-Forwarded-Proto
          value: "%REQ(:scheme)%"
    services:
    - name: authentik-server
      port: 80