apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-branding-pvc
  namespace: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs
