apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: planka
  namespace: planka
spec:
  virtualhost:
    fqdn: planka.etsmtl.club
    tls:
      secretName: planka-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    responseHeadersPolicy:
      set:
        - name: X-Frame-Options
          value: ALLOW
        - name: Content-Security-Policy
          value: frame-ancestors 'self' https://nextcloud.etsmtl.club
    services:
    - name: planka
      port: 1337
