apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-planka
  argocd.argoproj.io/sync-wave: "-1"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  instances: 1
  bootstrap:
    initdb:
      database: planka
      owner: planka
      secret:
        name: planka-cnpg-auth
  storage:
    size: 15Gi
    storageClass: cephfs