apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-nextcloud-backup
  namespace: nextcloud
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  instances: 3
  bootstrap:
    recovery:
      backup:
        name: cnpg-backup-schedule-20250520232600
  storage:
    size: 10Gi
    storageClass: cephfs
