apiVersion: v1
kind: Service
metadata:
  name: jdgets-outlinewiki-svc
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  clusterIP: None
  selector:
    app: jdgets-outlinewiki
