apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: raconteurs-

resources:
  - ../../../../../bases/grav
  - vault-secret.yaml

patches:
  - path: vault-patch.yaml
  - target:
      kind: HTTPProxy
      name: grav-ingress
    patch: |-
      - op: replace
        path: /spec/virtualhost/fqdn
        value: raconteurs.etsmtl.ca
      - op: replace
        path: /spec/virtualhost/tls/secretName
        value: raconteurs-grav-tls
      - op: replace
        path: /spec/routes/0/services/0/name
        value: raconteurs-grav
  - target:
      kind: Certificate
      name: grav-tls
    patch: |-
      - op: replace
        path: /spec/secretName
        value: raconteurs-grav-tls
      - op: replace
        path: /spec/commonName
        value: raconteurs.etsmtl.ca
      - op: replace
        path: /spec/dnsNames/0
        value: raconteurs.etsmtl.ca
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt-http
  - target:
      kind: RandomSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/data/raconteurs-grav/default/grav
  - target:
      kind: Deployment
      name: grav
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe
        value:
          tcpSocket:
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 60
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 6