apiVersion: apps/v1
kind: Deployment
metadata:
  name: grav
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: null
        vault.hashicorp.com/role: null
        vault.hashicorp.com/agent-inject-template-gitsync: null
        vault.hashicorp.com/agent-inject-template-admin_pwd: null
        vault.hashicorp.com/agent-inject-template-sre_pwd: null
        vault.hashicorp.com/agent-inject-template-salt: null
    spec:
      containers:
        - name: grav
          volumeMounts:
            - name: grav-vault-files
              mountPath: /vault/secrets
              readOnly: true
      volumes:
        - name: grav-vault-files
          secret:
            secretName: raconteurs-grav-vault-files
