apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
      - name: X-Forwarded-For
        value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      - name: X-Forwarded-Proto
        value: '%PROTOCOL%'
      - name: Upgrade
        value: websocket
    services:
    - name: nextcloud
      port: 8080
  virtualhost:
    fqdn: nextcloud.etsmtl.club
    tls:
      minimumProtocolVersion: "1.3"
      secretName: nextcloud-ingress-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nextcloud-internal
  namespace: nextcloud
spec:
  ingressClassName: contour-internal
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
      - name: X-Forwarded-For
        value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      - name: X-Forwarded-Proto
        value: '%PROTOCOL%'
      - name: Upgrade
        value: websocket
    services:
    - name: nextcloud
      port: 8080
  virtualhost:
    fqdn: nextcloud.etsmtl.club
    tls:
      minimumProtocolVersion: "1.3"
      secretName: nextcloud-ingress-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: collabora
  namespace: nextcloud
spec:
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
      - name: X-Forwarded-For
        value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      - name: X-Forwarded-Proto
        value: '%PROTOCOL%'
      - name: Upgrade
        value: websocket
    services:
    - name: collabora-collabora-online
      port: 9980
  virtualhost:
    fqdn: collabora-nextcloud.etsmtl.club
    tls:
      minimumProtocolVersion: "1.3"
      secretName: collabora-ingress-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: collabora-internal
  namespace: nextcloud
spec:
  ingressClassName: contour-internal
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
      - name: X-Forwarded-For
        value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      - name: X-Forwarded-Proto
        value: '%PROTOCOL%'
      - name: Upgrade
        value: websocket
    services:
    - name: collabora-collabora-online
      port: 9980
  virtualhost:
    fqdn: collabora-nextcloud.etsmtl.club
    tls:
      minimumProtocolVersion: "1.3"
      secretName: collabora-ingress-tls
