---
namespace: nextcloud
resources:
  # - secrets.yaml
  - postgresql.yaml
  - httpproxy.yaml
  - certificate.yaml
  - pvc.yaml
  - cronjob.yaml
  # - nextcloud-setup-job.yaml
patches:
  - target:
      kind: Deployment
      name: nextcloud
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nextcloud
      spec:
        template:
          metadata:
            labels:
              app.kubernetes.io/backup: velero
            annotations:
              backup.velero.io/backup-volumes: nextcloud-main
helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm
    version: 6.6.10
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: nextcloud-values.yaml
  - name: collabora-online
    repo: https://collaboraonline.github.io/online
    version: 1.1.38
    releaseName: collabora
    namespace: nextcloud
    valuesFile: collabora-values.yaml
configMapGenerator:
  - name: nextcloud-setup-job
    files:
      - job-files/external-sites.yaml
      - job-files/clubs.yaml
      - job-files/nextcloud-setup.bash
