apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: forgejo
  namespace: forgejo
spec:
  virtualhost:
    fqdn: git.etsmtl.club
    tls:
      secretName: forgejo-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
          enableWebsockets: true
          services:
            - name: forgejo-http
              port: 3000
              # Move header policy here and note the 's' in Headers
              requestHeadersPolicy:
                set:
                  - name: X-Forwarded-Proto
                    value: https
          timeoutPolicy:
            idle: 600s
            response: 600s
