apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  annotations:
    kube-score/ignore: pod-networkpolicy,container-image-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: matomo
          image: matomo:5.5.1-fpm
          imagePullPolicy: Always
          ports:
            - name: fpm
              containerPort: 9000
          env:
            - name: MATOMO_DATABASE_HOST
              value: matomo-mariadb
            - name: MATOMO_DATABASE_USERNAME
              value: matomo
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-config
                  key: MYSQL_PASSWORD
            - name: MATOMO_DATABASE_DBNAME
              value: matomo
            - name: MATOMO_DATABASE_ADAPTER
              value: "PDO_MYSQL"
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
