apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: common
spec:
  sourceRepos:
    - 'https://github.com/clubcedille/k8s-base.git'
    - 'https://*.github.io/helm-charts/'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-shared
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
    - namespace: '*'
      server: 'https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-shared'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-cedille-sandbox
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: 'https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-sandbox'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-cedille-production-v2
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: 'https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: LanETS
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'lanets-*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
