apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-tls
spec:
  secretName: loki-tls
  issuerRef:
    name: letsencrypt-etsmtl
    kind: ClusterIssuer
  commonName: loki.etsmtl.club
  dnsNames:
    - loki.etsmtl.club
