authentik:
  error_reporting:
    enabled: false

server:
  # Default image used by all authentik components. For GeoIP configuration, see the geoip values below.
  image:
    # -- If defined, a repository applied to all authentik deployments
    repository: ghcr.io/goauthentik/server
    # -- Overrides the global authentik whose default is the chart appVersion
    tag: "2026.5.0"
  ingress:
    enabled: false
    hosts:
      - auth.etsmtl.club
  replicas: 2
  pdb:
    enabled: true
    minAvailable: 1
  autoscaling:
    enabled: true
    maxReplicas: 5
    minReplicas: 2

worker:
  enabled: true
  name: worker
  replicas: 2
  pdb:
    enabled: true
    minAvailable: 1
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

defaultStorageClass: cephfs

global:
  storageClass: cephfs
  security:
    allowInsecureImages: true
  volumes:
    - name: authentik-branding
      persistentVolumeClaim:
        claimName: authentik-branding-pvc
  volumeMounts:
    - name: authentik-branding
      mountPath: /data
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  env:
    - name: AUTHENTIK_STORAGE__BACKEND
      value: "file"
    - name: AUTHENTIK_STORAGE__FILE__PATH
      value: "/data"
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_SECRET_KEY

    - name: AUTHENTIK_BOOTSTRAP_TOKEN
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_BOOTSTRAP_TOKEN
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_BOOTSTRAP_PASSWORD

    - name: AUTHENTIK_POSTGRESQL__HOST
      value: postgresql-authentik-rw
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-cnpg-app
          key: password

postgresql:
  enabled: false
