authentik:
  error_reporting:
    enabled: false

server:
  ingress:
    enabled: false
    hosts:
      - auth.etsmtl.club

defaultStorageClass: cephfs

global:
  storageClass: cephfs
  namespace: "authentik"
  security:
    allowInsecureImages: true
  volumes:
    - name: authentik-branding
      persistentVolumeClaim:
        claimName: authentik-branding-pvc
  volumeMounts:
    - name: authentik-branding
      mountPath: /media/custom/branding
  initContainers:
    - name: init-permissions
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          chown -R <1000>:<1000> /media/custom/branding
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_SECRET_KEY

    - name: AUTHENTIK_BOOTSTRAP_TOKEN
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_BOOTSTRAP_TOKEN
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_BOOTSTRAP_PASSWORD

    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_POSTGRES_PASSWORD

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: library/postgres
    tag: "17.4"
  auth:
    existingSecret: authentik-secrets
    secretKeys:
      adminPasswordKey: AUTHENTIK_POSTGRES_PASSWORD
      userPasswordKey: AUTHENTIK_POSTGRES_PASSWORD
  persistence:
    enabled: true
    storageClass: cephfs

redis:
  enabled: true
  image:
    registry: docker.io
    repository: library/redis
    tag: "8.2.1"
  persistence:
    enabled: true
    storageClass: cephfs
