apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docmost
  annotations:
    kube-score/ignore: pod-networkpolicy, pod-probes, container-security-context-readonlyrootfilesystem, container-security-context-privileged, container-security-context-user-group-id
spec:
  serviceName: docmost
  replicas: 2
  selector:
    matchLabels:
      app: docmost
  template:
    metadata:
      labels:
        app: docmost
    spec:
      containers:
        - env:
            - name: APP_URL
              value: https://wiki.etsmtl.club
            - name: REDIS_URL
              value: redis://redis.docmost.svc.cluster.local:6379
          image: docmost/docmost:0.21.0
          name: docmost
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: docmost-secrets
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data/storage
              name: docmost-pv-claim
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 1Gi
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
            fsGroup: 10000
            runAsNonRoot: true
            readOnlyRootFilesystem: fal
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
      initContainers:
        - name: init-myserver
          image: busybox:1.28
          command: ['sh', '-c', 'sudo chown -R 1000:1000 /app/data/storage']
          volumeMounts:
            - mountPath: /app/data/storage
              name: docmost-pv-claim
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: docmost-pv-claim
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 15Gi
        storageClassName: cephfs
