apiVersion: apps/v1
kind: Deployment
metadata:
  name: littlelink
  annotations:
    kube-score/ignore: container-image-tag,pod-networkpolicy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: littlelink
  template:
    metadata:
      labels:
        app: littlelink
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: littlelink
          image: timothystewart6/littlelink-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: littlelink-env
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 101
            runAsNonRoot: true            
            capabilities:
              drop:
                - ALL