apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: vaultwarden.etsmtl.club
  dnsNames:
    - vaultwarden.etsmtl.club