apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  virtualhost:
    fqdn: vaultwarden.etsmtl.club
    tls:
      secretName: vaultwarden-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
        enableWebsockets: true
        services:
          - name: vaultwarden
            port: 80
