apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vaultwarden-httpproxy
spec:
  virtualhost:
    fqdn: vaultwarden.etsmtl.club
    tls:
      secretName: vaultwarden-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      services:
        - name: vaultwarden
          port: 80
      enableWebsockets: true
