apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  annotations:
    kube-score/ignore: pod-networkpolicy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - chown -R 10001:10001 /data;
              chmod -R 770 /data;
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-storage
      containers:
        - name: vaultwarden
          image: vaultwarden/server:testing
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-storage
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: ADMIN_TOKEN

            - name: SSO_ENABLED
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_ENABLED

            - name: SSO_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_AUTHORITY

            - name: SSO_SCOPES
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_SCOPES
            
            - name: SSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_CLIENT_ID

            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_SCOPES

            - name: SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION

            - name: SSO_CLIENT_CACHE_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_CLIENT_CACHE_EXPIRATION

            - name: SSO_ONLY
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_ONLY

            - name: SSO_SIGNUPS_MATCH_EMAIL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_SIGNUPS_MATCH_EMAIL

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: vaultwarden-storage
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
