apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ctfd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ctfd
  project: k8s-shared
  source:
    repoURL: https://github.com/ClubCedille/k8s-shared.git
    path: apps/clubs/dci/ctfd/prod
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
