apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  project: k8s-shared
  sources:
    - repoURL: "https://github.com/ClubCedille/k8s-shared.git"
      path: apps/sonarqube/prod
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
