apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: Cedille2-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    audiences:
    - vault
    role: secret-reader
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: outline-secrets
spec:
  vaultAuthRef: Cedille2-auth
  type: kv-v1
  mount: kv
  path: data/Cedille2-outlinewiki/default/outline-secrets
  destination:
    name: outline-secrets
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: outline-postgresql
spec:
  vaultAuthRef: Cedille2-auth
  type: kv-v1
  mount: kv
  path: data/Cedille2-outlinewiki/default/outline-postgresql
  destination:
    name: outline-postgresql
    create: true
    type: kubernetes.io/basic-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: b2-creds
spec:
  vaultAuthRef: Cedille2-auth
  type: kv-v1
  mount: kv-system
  path: default_passwords/b2-creds
  destination:
    name: b2-creds
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dockerhub-secret
spec:
  vaultAuthRef: Cedille2-auth
  type: kv-v1
  mount: kv-system
  path: default_passwords/docker
  destination:
    name: dockerhub-secret
    create: true
    type: kubernetes.io/dockerconfigjson
