apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubero-ui-tls
spec:
  secretName: kubero-ui-tls
  issuerRef:
    name: letsencrypt-etsmtl
    kind: ClusterIssuer
  commonName: kubero.etsmtl.club
  dnsNames:
    - kubero.etsmtl.club
