apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubero-ui
spec:
  virtualhost:
    fqdn: kubero.etsmtl.club
    tls:
      secretName: kubero-ui-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: kubero
          port: 2000
      timeoutPolicy:
        idle: 600s
        response: 600s
