apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage-external
  namespace: argocd
spec:
  project: k8s-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: garage-external
  source:
    repoURL: https://github.com/ClubCedille/k8s-shared
    path: apps/garage-external
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
