apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: garage-operator
    releaseName: garage-operator
    repo: oci://ghcr.io/rajsinghtech/charts
    version: 0.7.7
    namespace: garage-operator-system
    includeCRDs: true

resources:
  - resources/namespace-operator.yaml
  - resources/vault-auth.yaml
  - resources/vault-secret.yaml
  - resources/garagecluster.yaml
