apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
  name: grav-smoke-test-grav
spec:
  authentication:
    path: kubernetes
    role: config-admin
  path: github
  repositories:
    - grav-smoke-test.prodv2.cedille.club
  organizationName: ClubCedille