apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: matomo
  namespace: matomo
resources:
  - prod/certificate.yaml
  - prod/httpproxy.yaml
helmCharts:
  - name: matomo
    version: "2024.10.2"
    repo: "oci://registry-1.docker.io/bitnamicharts/matomo"
    releaseName: "matomo"
    namespace: matomo
    valuesFile: "helm/values.yaml"
