apiVersion: v1
kind: Service
metadata:
  name: conjure-service
spec:
  ports:
    - name: http
      targetPort: 3000
      protocol: TCP
      port: 3000
  type: ClusterIP
  selector:
    app: conjure-service
