---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ets-ctfd-tls
spec:
  secretName: ets-ctfd-tls
  issuerRef:
    name: letsencrypt-etsmtl
    kind: ClusterIssuer
  commonName: ing101.etsmtl.club
  dnsNames:
    - ing101.etsmtl.club
