apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ctfd-httpproxy
spec:
  virtualhost:
    fqdn: ing101.fraternitedupiranha.com
    tls:
      secretName: frat-ctfd-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      services:
        - name: ctfd
          port: 80
      enableWebsockets: true
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ctfd-httpproxy
spec:
  virtualhost:
    fqdn: ing101.piranha.cedille.club
    tls:
      secretName: cedille-ctfd-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      services:
        - name: ctfd
          port: 80
      enableWebsockets: true
