apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: campusparent-cnpg-sync
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: root
      path: kv/data/campusparent/default/postgresql-campusparent
  output:
    name: cnpg-config
    stringData:
      username: 'campusparent'
      password: '{{ .root.password }}'
    type: kubernetes.io/basic-auth
    labels:
      app: campusparent
