apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: postgresql-campusparent
spec:
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: kv/data/campusparent/default
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
