apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: docmost-staging
spec:
  virtualhost:
    fqdn: docmost.staging.etsmtl.club
    tls:
      secretName: docmost-staging-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: docmost
          port: 3000
      timeoutPolicy:
        idle: 600s
        response: 600s
