apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: grav-vault-files
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: git
      path: github/token/grav-smoke-test-grav
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: admin
      path: kv/data/grav-smoke-test-grav/default/grav/grav-smoke-test-grav-init-pwd
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: sre
      path: kv/data/grav-smoke-test-grav/default/grav/grav-smoke-test-grav-sre-pwd
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: grav
      path: kv/data/grav-smoke-test-grav/default/grav/grav-smoke-test-grav-salt
  output:
    name: grav-smoke-test-grav-vault-files
    stringData:
      gitsync: |
        enabled: true
        folders:
          - pages
          - plugins
          - themes
          - config
        SyncNotice: null
        sync:
          on_save: true
          on_delete: true
          on_media: true
          cron_enable: true
          cron_at: '*/10 * * * *'
        local_repository: null
        repository: 'https://github.com/ClubCedille/grav-smoke-test.prodv2.cedille.club.git'
        no_user: '0'
        user: x-access-token
        password: "{{ .git.token }}"
        webhook_enabled: '1'
        webhook: '/_git_webhook'
        branch: main
        remote:
          name: origin
          branch: main
        git:
          author: gitsync
          message: '(Grav GitSync) Automatic Commit'
          name: GitSync
          email: git-sync@trilby.media
          bin: git
          ignore: null
          private_key: null
        logging: true
      admin_pwd: |
        state: enabled
        email: admin@grav-smoke-test.prodv2.cedille.club
        username: admin
        fullname: admin
        title: Administrator
        access:
          admin:
            login: true
            super: true
          site:
            login: true
        password: "{{ .admin.password }}"
      sre_pwd: |
        state: enabled
        email: sre@cedille.club
        username: sre
        fullname: SRE
        title: SRE
        access:
          admin:
            login: true
            super: true
          site:
            login: true
        password: "{{ .sre.password }}"
      salt: |
        salt: "{{ .grav.salt }}"
    type: Opaque
