apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-crabe
  annotations:
    kube-score/ignore: >-
      container-image-tag,
      pod-networkpolicy,
      container-security-context-readonlyrootfilesystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-crabe
  template:
    metadata:
      labels:
        app: webapp-crabe
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: storage
          emptyDir: {}
      initContainers:
        - name: fix-storage-perms
          image: ghcr.io/crabe-etsmtl/crabe-atelier:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - >-
              mkdir -p
              /var/www/storage/framework/sessions
              /var/www/storage/framework/views
              /var/www/storage/framework/cache/data
              /var/www/storage/logs
              &&
              chown -R 10001:10001 /var/www
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: storage
              mountPath: /var/www/storage
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
      containers:
        - name: webapp-crabe
          envFrom:
            - configMapRef:
                name: webapp-crabe-env
            - secretRef:
                name: webapp-crabe-secrets
          image: ghcr.io/crabe-etsmtl/crabe-atelier:latest
          imagePullPolicy: Always
          command: ["composer", "run", "k8s"]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 600m
              memory: 512Mi
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: storage
              mountPath: /var/www/storage
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
