apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: outline
spec:
  virtualhost:
    fqdn: outline.etsmtl.club
    tls:
      secretName: outline-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: outline
          port: 3000
      timeoutPolicy:
        idle: 600s
        response: 600s
