apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-extra-ips
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-75"
spec:
  project: k8s-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    repoURL: https://github.com/ClubCedille/k8s-shared.git
    path: system/metallb-extra
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
