apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saveursdegenie-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: website=ghcr.io/clubcedille/saveursdegenie.etsmtl.ca:latest
    argocd-image-updater.argoproj.io/website.update-strategy: digest
    argocd-image-updater.argoproj.io/website.pull-secret: pullsecret:argocd/ghcr-clubcedille-secret
spec:
  project: k8s-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: saveursdegenie
  source:
    repoURL: https://github.com/ClubCedille/k8s-shared
    path: apps/clubs/saveursdegenie/website/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true