apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: coder-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    audiences:
      - vault
    role: secret-reader
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coder-oidc-secret
spec:
  vaultAuthRef: coder-auth
  type: kv-v1
  mount: kv
  path: data/coder/default/coder-oidc-secret
  destination:
    name: coder-oidc-secret
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: b2-creds
spec:
  vaultAuthRef: coder-auth
  type: kv-v1
  mount: kv-system
  path: default_passwords/b2-creds
  destination:
    name: b2-creds
    create: true
