apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/
  - ingress.yaml
  - vault-secret.yaml
  - configmap.yaml

patchesStrategicMerge:
  - patch-image.yaml

patches:
  - target:
      kind: Deployment
      name: webapp-crabe
    patch: |
      - op: remove
        path: /spec/template/spec/containers/0/env
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: webapp-crabe-env
          - secretRef:
              name: webapp-crabe-secrets
