apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/
  - ingress.yaml
  - vault-secret.yaml
  - configmap.yaml

patches:
  - target:
      kind: Deployment
      name: webapp-crabe
    patch: |
      - op: replace
        path: /spec/template/spec/initContainers/0/image
        value: ghcr.io/crabe-etsmtl/crabe-atelier:staging
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/crabe-etsmtl/crabe-atelier:staging
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: "1"
            memory: 1Gi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: 256Mi
  - target:
      kind: Service
      name: crabe-svc
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 8000
  - target:
      kind: Ingress
      name: staging-crabe-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 8000