apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: ghcr-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: docker
      path: kv-system/default_passwords/docker-crabe
  output:
    name: ghcr-secret
    stringData:
      .dockerconfigjson: '{{ b64dec .docker.config }}'
    type: kubernetes.io/dockerconfigjson
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: webapp-crabe-config
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: crabe
      path: kv/data/webapp-crabe-staging/default/config
  output:
    name: webapp-crabe-secrets
    stringData:
      APP_KEY: '{{ .crabe.APP_KEY }}'
      DB_USERNAME: '{{ .crabe.DB_USERNAME }}'
      DB_PASSWORD: '{{ .crabe.DB_PASSWORD }}'
      DB_ROOT_PASSWORD: '{{ .crabe.DB_ROOT_PASSWORD }}'
      MYSQL_DATABASE: '{{ .crabe.MYSQL_DATABASE }}'
      MYSQL_PASSWORD: '{{ .crabe.MYSQL_PASSWORD }}'
      MYSQL_ROOT_PASSWORD: '{{ .crabe.MYSQL_ROOT_PASSWORD }}'
      MYSQL_USER: '{{ .crabe.MYSQL_USER }}'
    type: opaque
