apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/qdrant
  - vault-secret.yaml

images:
  - name: qdrant/qdrant
    digest: sha256:0bd98fa7977f1e75694779359ca4e212822e5a71334e28421182f72f209d5286
