apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: k8s-shared
  sources:
    - chart: grafana
      helm:
        releaseName: grafana
        valueFiles:
          - $values/apps/grafana/helm/values.yaml
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 10.5.15
    - repoURL: "https://github.com/ClubCedille/k8s-shared.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/ClubCedille/k8s-shared.git"
      path: apps/grafana/resources
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
