apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veloom-wordpress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: veloom
  source:
    repoURL: https://github.com/ClubCedille/k8s-shared
    path: apps/clubs/veloom/wordpress/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true