apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: ghcr-markets-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: docker
      path: kv-system/default_passwords/docker-markets
  output:
    name: ghcr-markets-secret
    stringData:
      .dockerconfigjson: '{{ b64dec .docker.config }}'
    type: kubernetes.io/dockerconfigjson
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: markets-env-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: markets
      path: kv/data/markets-dev/default/config
  output:
    name: markets-env-secret
    stringData:
      API_TOKEN_SALT: '{{ .markets.API_TOKEN_SALT }}'
      API_URL: '{{ .markets.API_URL }}'
      DJANGO_SUPERUSER_EMAIL: '{{ .markets.DJANGO_SUPERUSER_EMAIL }}'
      DJANGO_SUPERUSER_PASSWORD: '{{ .markets.DJANGO_SUPERUSER_PASSWORD }}'
      DJANGO_SUPERUSER_USERNAME: '{{ .markets.DJANGO_SUPERUSER_USERNAME }}'
      EMAIL_ID: '{{ .markets.EMAIL_ID }}'
      EMAIL_PW: '{{ .markets.EMAIL_PW }}'
      FMP_API_KEY: '{{ .markets.FMP_API_KEY }}'
      FRONTEND_URL: '{{ .markets.FRONTEND_URL }}'
      GITHUB_BUG_REPORT_TOKEN: '{{ .markets.GITHUB_BUG_REPORT_TOKEN }}'
      MODERATOR_PASSWORD: '{{ .markets.MODERATOR_PASSWORD }}'
      PASSWORD_RESET_REDIRECT_URL: '{{ .markets.PASSWORD_RESET_REDIRECT_URL }}'
      POSTGRES_DB: '{{ .markets.POSTGRES_DB }}'
      POSTGRES_HOST: '{{ .markets.POSTGRES_HOST }}'
      POSTGRES_PASSWORD: '{{ .markets.POSTGRES_PASSWORD }}'
      POSTGRES_PORT: '{{ .markets.POSTGRES_PORT }}'
      POSTGRES_USER: '{{ .markets.POSTGRES_USER }}'
      REGISTRATION_KEY: '{{ .markets.REGISTRATION_KEY }}'
      SALT_SECRET_KEY: '{{ .markets.SALT_SECRET_KEY }}'
      VITE_API_URL: '{{ .markets.VITE_API_URL }}'
    type: opaque