apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jdgets-outlinewiki
  namespace: argocd
spec:
  destination:
    namespace: jdgets-outlinewiki
    server: https://kubernetes.default.svc
  project: k8s-shared
  source:
    path: apps/clubs/jdgets/outlinewiki/prod
    repoURL: https://github.com/ClubCedille/k8s-shared
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
