apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  annotations:
    kube-score/ignore: pod-networkpolicy, container-security-context-readonlyrootfilesystem, container-security-context-user-group-id, container-image-pull-policy, pod-probes
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
        - name: mysql
          image: mysql:9.6.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ctfd-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ctfd-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ctfd-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ctfd-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-pv-claim
              mountPath: /var/lib/mysql
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 2000m
              memory: 2Gi
              ephemeral-storage: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: mysql-pv-claim
      spec:
        storageClassName: cephfs
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
