apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubero-tls
spec:
  secretName: kubero-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: kubero.etsmtl.club
  dnsNames:
    - kubero.etsmtl.club
