apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: docmost
spec:
  virtualhost:
    fqdn: kubero.etsmtl.club
    tls:
      secretName: kubero-tls
      minimumProtocolVersion: "1.3"
  routes:
    - conditions:
        - prefix: /
      services:
        - name: kubero
          port: 3000
