apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: outline-cedille
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    kube-score/ignore: pod-networkpolicy, container-security-context-readonlyrootfilesystem, container-security-context-privileged, container-security-context-user-group-id, container-image-tag
spec:
  serviceName: outline-cedille
  replicas: 2
  selector:
    matchLabels:
      app: outline-cedille
  template:
    metadata:
      labels:
        app: outline-cedille
    spec:
      containers:
        - env:
            - name: URL
              value: https://cedille.etsmtl.club
            - name: REDIS_URL
              value: redis://redis-cedille.outline-cedille.svc.cluster.local:6379
            - name: REDIS_COLLABORATION_URL
              value: redis://redis-cedille.outline-cedille.svc.cluster.local:6379
            - name: FILE_STORAGE
              value: s3
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_S3_UPLOAD_BUCKET_URL
              value: "http://10.0.21.59:7480"
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "true"
            - name: AWS_S3_ACL
              value: private
            - name: AWS_S3_UPLOAD_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: outline-cedille-attachments
                  key: BUCKET_NAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: outline-cedille-attachments
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: outline-cedille-attachments
                  key: AWS_SECRET_ACCESS_KEY
          image: outlinewiki/outline:1.10.1
          name: outline
          imagePullPolicy: Always
          # https://github.com/outline/outline/blob/main/.env.sample
          envFrom:
            - secretRef:
                name: outline-secrets
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
              ephemeral-storage: 1Gi
          readinessProbe:
            httpGet:
              path: /_health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: dockerhub-pull
      restartPolicy: Always
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: outline-cedille-attachments
spec:
  generateBucketName: outline-cedille-attachments
  storageClassName: ceph-bucket
