apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: matomo
  namespace: matomo
spec:
  virtualhost:
    fqdn: matomo.etsmtl.club
    tls:
      secretName: matomo-tls
  routes:
    - conditions:
      - prefix: /
        services:
          - name: matomo
            port: 80
    - conditions:
      - prefix: /websocket
        enableWebsockets: true
        services:
          - name: matomo
            port: 80
