---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: matomo-mariadb-root
  namespace: matomo
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: matomo-mariadb/data/root
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: matomo-mariadb-replication
  namespace: matomo
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: matomo-mariadb/data/replication
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: matomo-mariadb-user
  namespace: matomo
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: matomo-mariadb/data/user
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
