apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: ghcr-clubcedille-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: docker
      path: kv-system/default_passwords/docker
  output:
    name: ghcr-clubcedille-secret
    stringData:
      .dockerconfigjson: '{{ b64dec .docker.config }}'
    type: kubernetes.io/dockerconfigjson
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: matomo-mariadb-sync
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: root
      path: kv/data/matomo/default/root
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: user
      path: kv/data/matomo/default/user

  output:
    name: mariadb-config
    stringData:
      MYSQL_ROOT_PASSWORD: '{{ .root.password }}'
      MYSQL_PASSWORD: '{{ .user.password }}'
    type: Opaque
    labels:
      app: matomo
