apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: penpot-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: penpot
  source:
    path: apps/clubs/penpot
    repoURL: https://github.com/ClubCedille/k8s-shared
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true